image: maven:3-jdk-8

stages:
  - build
  - test
#
#before_script:
#  - echo $CI_PROJECT_PATH
#  - docker-compose -f $CI_PROJECT_PATH up -d
#
#after_script:
#  - docker rm -f $(docker ps -q)

build:
  stage: build
  image: docker:latest
  script:
    - apk add --no-cache docker-compose
    - docker-compose -f $CI_PROJECT_PATH up -d
    - mvn package
    - cat target/site/jacoco/index.html
    - docker rm -f $(docker ps -q)
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    paths:
      - target/
    expire_in: 1 week

test:
  stage: test
  script:
    - mvn package
    - cat target/site/jacoco/index.html
  coverage: "/Total.*?([0-9]{1,3})%/"

