image: maven:3-jdk-8

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn package
    - cat target/site/jacoco/index.html
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    paths:
      - target/
    expire_in: 1 week

test:
  stage: test
  script:
    - mvn package
    - cat target/site/jacoco/index.html
  coverage: "/Total.*?([0-9]{1,3})%/"

