version: '3'
services:
  mysql_dev:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=marvel-api
      - MYSQL_DATABASE=marvel-api
      - MYSQL_USER=marvel-api
      - MYSQL_PASSWORD=marvel-api
    expose:
      - '3306'
    ports:
      - '3306:3306'